bindAddr = "0.0.0.0"
bindPort = 7000

webServer.addr = "172.24.43.161"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

log.to = "/etc/frp/frps.log"
log.level = "warn"
log.maxDays = 365